healthcare_mdm:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'HMDM_DEV_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'HMDM_DEV') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'HMDM_WH') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'STAGING') }}"
      threads: 4