healthcare_mdm:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: AXIVKAP-PF58156
      user: HUBM
      password: "@Devansh#4552!"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
      database: HMDM_DEV
      warehouse: HMDM_WH
      schema: STAGING
      threads: 4