-- ============================================================
-- Healthcare_Master_Data_Management - Snowflake DDL
-- Layer: STAGING
-- Synced from Databricks HMDM_DEV.staging.* by push_to_snowflake.py
-- Column names match Databricks Delta tables exactly.
-- ============================================================
USE DATABASE HMDM_DEV;
USE SCHEMA STAGING;

-- FIX (Sep 25 2026): Child tables now use generic 9-column schema matching
-- Databricks child tables. Fixed type mismatches: gender VARIANT->VARCHAR,
-- mdm_batch_id NUMBER->VARCHAR, added missing Batch_ID column.

-- HCP_NAME staging table (16 columns - includes HCP-specific name fields)
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCP_NAME (
    "source_name" VARCHAR(4000),
    "country_code" VARCHAR(4000),
    "create_date" VARCHAR(4000),
    "first_name" VARCHAR(4000),
    "full_name" VARCHAR(4000),
    "gender" VARCHAR(4000),
    "iqvia_id" VARCHAR(4000),
    "last_name" VARCHAR(4000),
    "mdm_entity_type" VARCHAR(4000),
    "middle_name" VARCHAR(4000),
    "professional_type" VARCHAR(4000),
    "response_json" VARCHAR(4000),
    "title" VARCHAR(4000),
    "mdm_batch_id" VARCHAR(4000),
    "Batch_ID" VARCHAR(4000),
    "Load_Date" TIMESTAMP_NTZ
);

-- Generic child table schema (9 columns - shared by all HCP and HCO child tables)
-- HCP child tables have ONLY generic columns (no entity-specific fields).
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCP_CHILD_GENERIC (
    "mdm_batch_id" VARCHAR(4000),
    "source_name" VARCHAR(4000),
    "iqvia_id" VARCHAR(4000),
    "country_code" VARCHAR(4000),
    "create_date" VARCHAR(4000),
    "mdm_entity_type" VARCHAR(4000),
    "response_json" VARCHAR(4000),
    "Batch_ID" VARCHAR(4000),
    "Load_Date" TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCP_ADDRESS LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCP_SPECIALTY LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCP_IDENTIFICATION LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCP_PHONE LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCP_EMAIL LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCP_ALTERNATE_NAME LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCP_EDUCATION LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCP_TENDENCIES LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCP_ORIGIN_UNIVERSITY LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCP_TAX LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCP_LANGUAGE LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCP_HCO_AFFILIATION LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;

-- HCP_LICENSE (kept from original DDL, not synced from Databricks)
-- Column name uses X_infa360_ prefix to match existing Snowflake table.
-- The dbt stg_HCP_LICENSE model uses NULL casts (WHERE 1=0) so it does
-- not depend on this column name.
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCP_LICENSE (
    "X_infa360_License" VARCHAR(4000)
);

-- HCO_NAME staging table (11 columns - includes HCO-specific org fields)
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCO_NAME (
    "mdm_batch_id" VARCHAR(4000),
    "source_name" VARCHAR(4000),
    "iqvia_id" VARCHAR(4000),
    "country_code" VARCHAR(4000),
    "create_date" VARCHAR(4000),
    "mdm_entity_type" VARCHAR(4000),
    "response_json" VARCHAR(4000),
    "organization_name" VARCHAR(4000),
    "organization_type" VARCHAR(4000),
    "Batch_ID" VARCHAR(4000),
    "Load_Date" TIMESTAMP_NTZ
);

-- HCO child tables (8 tables - same generic 9-column schema as HCP child tables)
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCO_ADDRESS LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCO_ALTERNATE_NAME LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCO_IDENTIFICATION LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCO_SPECIALTY LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCO_PHONE LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCO_EMAIL LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCO_TAX LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;
CREATE TABLE IF NOT EXISTS HMDM_DEV.STAGING.HCO_HIERARCHY LIKE HMDM_DEV.STAGING.HCP_CHILD_GENERIC;