-- 1. STAGING row counts
SELECT 'HCP_ADDRESS' AS T, COUNT(*) AS R FROM HMDM_DEV.STAGING.HCP_ADDRESS UNION ALL
SELECT 'HCP_SPECIALTY', COUNT(*) FROM HMDM_DEV.STAGING.HCP_SPECIALTY UNION ALL
SELECT 'HCP_IDENTIFICATION', COUNT(*) FROM HMDM_DEV.STAGING.HCP_IDENTIFICATION UNION ALL
SELECT 'HCP_PHONE', COUNT(*) FROM HMDM_DEV.STAGING.HCP_PHONE UNION ALL
SELECT 'HCP_EMAIL', COUNT(*) FROM HMDM_DEV.STAGING.HCP_EMAIL UNION ALL
SELECT 'HCP_ALTERNATE_NAME', COUNT(*) FROM HMDM_DEV.STAGING.HCP_ALTERNATE_NAME UNION ALL
SELECT 'HCP_EDUCATION', COUNT(*) FROM HMDM_DEV.STAGING.HCP_EDUCATION UNION ALL
SELECT 'HCP_TENDENCIES', COUNT(*) FROM HMDM_DEV.STAGING.HCP_TENDENCIES UNION ALL
SELECT 'HCP_ORIGIN_UNIVERSITY', COUNT(*) FROM HMDM_DEV.STAGING.HCP_ORIGIN_UNIVERSITY UNION ALL
SELECT 'HCP_TAX', COUNT(*) FROM HMDM_DEV.STAGING.HCP_TAX UNION ALL
SELECT 'HCP_LANGUAGE', COUNT(*) FROM HMDM_DEV.STAGING.HCP_LANGUAGE UNION ALL
SELECT 'HCP_HCO_AFFILIATION', COUNT(*) FROM HMDM_DEV.STAGING.HCP_HCO_AFFILIATION UNION ALL
SELECT 'HCO_NAME', COUNT(*) FROM HMDM_DEV.STAGING.HCO_NAME UNION ALL
SELECT 'HCO_ADDRESS', COUNT(*) FROM HMDM_DEV.STAGING.HCO_ADDRESS UNION ALL
SELECT 'HCO_ALTERNATE_NAME', COUNT(*) FROM HMDM_DEV.STAGING.HCO_ALTERNATE_NAME UNION ALL
SELECT 'HCO_IDENTIFICATION', COUNT(*) FROM HMDM_DEV.STAGING.HCO_IDENTIFICATION UNION ALL
SELECT 'HCO_SPECIALTY', COUNT(*) FROM HMDM_DEV.STAGING.HCO_SPECIALTY UNION ALL
SELECT 'HCO_PHONE', COUNT(*) FROM HMDM_DEV.STAGING.HCO_PHONE UNION ALL
SELECT 'HCO_EMAIL', COUNT(*) FROM HMDM_DEV.STAGING.HCO_EMAIL UNION ALL
SELECT 'HCO_TAX', COUNT(*) FROM HMDM_DEV.STAGING.HCO_TAX UNION ALL
SELECT 'HCO_HIERARCHY', COUNT(*) FROM HMDM_DEV.STAGING.HCO_HIERARCHY
ORDER BY T;

-- 2. MASTER row counts
SELECT 'HCP_SPECIALTY' AS T, COUNT(*) AS R FROM HMDM_DEV.MASTER.HCP_SPECIALTY UNION ALL
SELECT 'HCP_ALTERNATE_NAME', COUNT(*) FROM HMDM_DEV.MASTER.HCP_ALTERNATE_NAME UNION ALL
SELECT 'HCP_EDUCATION', COUNT(*) FROM HMDM_DEV.MASTER.HCP_EDUCATION UNION ALL
SELECT 'HCP_IDENTIFICATION', COUNT(*) FROM HMDM_DEV.MASTER.HCP_IDENTIFICATION UNION ALL
SELECT 'HCO', COUNT(*) FROM HMDM_DEV.MASTER.HCO UNION ALL
SELECT 'HCO_NAME', COUNT(*) FROM HMDM_DEV.MASTER.HCO_NAME UNION ALL
SELECT 'HCO_ALTERNATE_IDENTIFIER', COUNT(*) FROM HMDM_DEV.MASTER.HCO_ALTERNATE_IDENTIFIER UNION ALL
SELECT 'HCO_PHONE', COUNT(*) FROM HMDM_DEV.MASTER.HCO_PHONE UNION ALL
SELECT 'HCO_SPECIALTY', COUNT(*) FROM HMDM_DEV.MASTER.HCO_SPECIALTY
ORDER BY T;

-- 3. Sample data check
SELECT * FROM HMDM_DEV.STAGING.HCP_ADDRESS LIMIT 3;
SELECT * FROM HMDM_DEV.MASTER.HCO LIMIT 2;

-- 4. Table schemas
DESCRIBE TABLE HMDM_DEV.STAGING.HCP_ADDRESS;
DESCRIBE TABLE HMDM_DEV.MASTER.HCO;



==================================================================================================================

